name = "edgetunnel"
main = "_worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

[[kv_namespaces]]
binding = "KV"
id = "1cf3fa00920c41739a4295c4c3cb5747"